"""Static crop-name options derived from the public 高雄農來訊 CropVType catalog."""

# Keep this tuple sorted and dependency-free. Config forms must not contact the
# optional agricultural provider merely to render a disabled-by-default field.
CROP_NAME_OPTIONS = (
    "不結球白菜",
    "佛手瓜",
    "其他果樹",
    "其他果菜",
    "其他柑桔",
    "其他莖菜",
    "其他菇類",
    "其他葉菜",
    "冬瓜",
    "南瓜",
    "可可椰子",
    "四季豆",
    "大心芥菜",
    "大芥菜",
    "太空包香菇",
    "山藥",
    "山蘇",
    "巨峰葡萄",
    "扁蒲",
    "抱子甘藍",
    "改良種芒果",
    "文旦柚",
    "木瓜",
    "木耳",
    "本地種芒果",
    "李",
    "枇杷",
    "柳橙",
    "柿",
    "桃",
    "桑",
    "桶柑",
    "梅",
    "梨",
    "棗",
    "椪柑",
    "楊桃",
    "楊梅",
    "樹薯",
    "檸檬",
    "毛豆",
    "洋菇",
    "洋蔥",
    "洋香瓜",
    "洛神葵",
    "溫洲蜜柑",
    "火鶴花",
    "牛蒡",
    "玫瑰",
    "甘藍",
    "甘藷",
    "甜椒",
    "番石榴",
    "番荔枝(大目種)",
    "番荔枝(鳳梨釋迦)",
    "白木耳",
    "白柚",
    "百香果",
    "皇帝豆",
    "竹筍",
    "節瓜(毛瓜)",
    "紅龍果",
    "結球白菜",
    "結頭菜",
    "絲瓜",
    "羅勒",
    "義大利葡萄",
    "胡瓜",
    "胡蘿蔔",
    "芋",
    "芥藍",
    "芫荽",
    "花椰菜",
    "花豆",
    "芹菜",
    "苦瓜",
    "茂谷柑",
    "茄子",
    "茭白筍",
    "茴香",
    "茼蒿",
    "草莓",
    "草菇",
    "荔枝",
    "荸薺",
    "莧菜",
    "菜豆(豇豆)",
    "菠菜",
    "菱角",
    "萊姆",
    "萵苣",
    "落花生",
    "葡萄柚",
    "蒜頭",
    "蓮藕",
    "蓮霧",
    "蔥",
    "蔥頭",
    "蕹菜",
    "薑",
    "蘆筍",
    "蘋果",
    "蘿蔔",
    "蠔菇",
    "蠶豆",
    "西瓜",
    "豆薯",
    "豌豆(荷蘭豆)",
    "越瓜",
    "辣椒",
    "酪梨",
    "金柑",
    "金針菇",
    "金針菜",
    "青花菜",
    "青蒜",
    "韭菜",
    "食用玉米",
    "食用番茄",
    "香瓜",
    "香蕉",
    "馬鈴薯",
    "鳳梨",
    "鵲豆(肉豆)",
    "黃秋葵",
    "龍眼",
    "龍鬚菜",
)

# Labels remain human-friendly while selector values stay exact provider C_NAME
# values, preventing common Taiwanese names from becoming unsupported filters.
CROP_NAME_ALIASES = {
    "不結球白菜": "小白菜",
    "佛手瓜": "隼人瓜",
    "扁蒲": "瓠瓜／蒲瓜",
    "樹薯": "木薯",
    "甘藍": "高麗菜",
    "甘藷": "地瓜",
    "番石榴": "芭樂",
    "番荔枝(大目種)": "釋迦",
    "節瓜(毛瓜)": "毛瓜",
    "結球白菜": "包心白菜",
    "羅勒": "九層塔",
    "胡瓜": "小黃瓜",
    "芫荽": "香菜",
    "菜豆(豇豆)": "長豆",
    "蕹菜": "空心菜",
    "茭白筍": "美人腿",
    "落花生": "花生",
    "豌豆(荷蘭豆)": "荷蘭豆",
    "金柑": "金棗",
    "青花菜": "綠花椰菜",
    "青蒜": "蒜苗",
    "食用玉米": "玉米",
    "食用番茄": "番茄",
    "馬鈴薯": "洋芋",
}


def crop_select_options() -> tuple[dict[str, str], ...]:
    """Return homogeneous value/label options using exact provider values."""
    return tuple(
        {
            "value": name,
            "label": (
                f"{name}（{CROP_NAME_ALIASES[name]}）"
                if name in CROP_NAME_ALIASES
                else name
            ),
        }
        for name in CROP_NAME_OPTIONS
    )
